pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f jenkins/java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Create Tomcat Image') {
            steps {
                script {
                    echo "Copying WAR artifacts"
                    copyArtifacts filter: '**/*.war', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER)
                    echo "Building Docker image"
                    sh '''
                    original_pwd=$(pwd -P)
                    cd jenkins/java-tomcat-sample
                    docker build -t localtomcatimg:$BUILD_NUMBER .
                    cd $original_pwd
                    '''
                }
            }
        }
        stage('Deploy to Stagging Env') {
            steps {
                echo "Running app on stagging env"
                sh '''
                docker stop tomcatInstanceStaging || true
                docker rm tomcatInstanceStaging || true
                docker run -itd --name tomcatInstanceStaging -p 8082:8080 localtomcatimg:$BUILD_NUMBER
                sh '''
            }
        }
    }
}
