pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f jenkins/java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Create Tomcat Image') {
            steps {
                script {
                    echo "Copying WAR artifacts"
                    copyArtifacts filter: '**/*.war', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER)
                    echo "Building Docker image"
                    sh '''
                    original_pwd=$(pwd -P)
                    cd jenkins/java-tomcat-sample
                    docker build -t localtomcatimg:$BUILD_NUMBER .
                    cd $original_pwd
                    '''
                }
            }
        }
        stage('Push Docker Image to Local Registry') {
            steps {
                script {
                    echo "Starting Local Docker Registry"
                    sh 'docker run -d -p 5000:5000 --restart=always --name registry registry:2'
                    echo "Tagging the Docker image"
                    sh "docker tag localtomcatimg:$BUILD_NUMBER localhost:5000/localtomcatimg:$BUILD_NUMBER"
                    echo "Pushing the Docker image to Local Registry"
                    sh "docker push localhost:5000/localtomcatimg:$BUILD_NUMBER"
                }
            }
        }
    }
}
